import { BsClipboardCheck } from "react-icons/bs";
import { BiEditAlt } from "react-icons/bi";
import { TbTrash } from "react-icons/tb";
import { RiArrowDownSFill } from "react-icons/ri";
import { AiOutlineArrowLeft } from "react-icons/ai";
import { BsInstagram } from "react-icons/bs";
import { RiFacebookCircleLine } from "react-icons/ri";
import { FiTwitter } from "react-icons/fi";
import { TbBrandTiktok } from "react-icons/tb";
import { RiAdminLine } from "react-icons/ri";
import { MdFavoriteBorder } from "react-icons/md";
import { BiShoppingBag } from "react-icons/bi";
import { MdKeyboardDoubleArrowLeft } from "react-icons/md";
import { MdKeyboardDoubleArrowRight } from "react-icons/md";
import { IoMdCloseCircleOutline } from "react-icons/io";
import { BiStore } from "react-icons/bi";
import { BiHome } from "react-icons/bi";
import { ImLoop2 } from "react-icons/im";
import { FaRegEnvelope } from "react-icons/fa";
import { IoIosKeypad } from "react-icons/io";
import { HiPlus } from "react-icons/hi";
import { HiMinus } from "react-icons/hi";
import {BsBasket} from "react-icons/bs";

export const ClipboardCheckIcon = BsClipboardCheck;
export const EditAltIcon = BiEditAlt;
export const TrashIcon = TbTrash;
export const ArrowDownSFillIcon = RiArrowDownSFill;
export const OutlineArrowLeftIcon = AiOutlineArrowLeft;
export const InstagramIcon = BsInstagram;
export const FacebookCircleLineIcon = RiFacebookCircleLine;
export const TwitterIcon = FiTwitter;
export const BrandTiktokIcon = TbBrandTiktok;
export const AdminLineIcon = RiAdminLine;
export const FavoriteBorderIcon = MdFavoriteBorder;
export const ShoppingBagIcon = BiShoppingBag;
export const KeyboardDoubleArrowLeftIcon = MdKeyboardDoubleArrowLeft;
export const KeyboardDoubleArrowRightIcon = MdKeyboardDoubleArrowRight;
export const MdCloseCircleOutlineIcon = IoMdCloseCircleOutline;
export const Store = BiStore;
export const Home = BiHome;
export const Loop2 = ImLoop2;
export const RegEnvelope = FaRegEnvelope;
export const IosKeypad = IoIosKeypad;
export const Plus = HiPlus;
export const Minus = HiMinus;
export const Basket = BsBasket
